[general]
    winX = integer(default=50)
    winY = integer(default=50)
    winH = integer(default=600)
    winW = integer(default=800)
    auiPerspective = string(default='')
    state = option('normal', 'maxim', default='maxim')
    fileHistory = list(default=list())
    prevFile = string(default='')
    expyvrVersion = string(default='')